config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'
  resources :users do
    member do
      get :reset_password
      patch :activate
      patch :deactivate
    end
  end
  resources :restaurants do
    resources :photos, only: [:destroy]
    member do
      patch :activate
      patch :deactivate
    end
  end
  resources :restaurant_batches, only: [:new, :create, :show]
  resources :food_types
  resources :facilities
  resources :areas

  get "/confirm_email/:token", to: "email_confirmations#update", as: "confirm_email"

  namespace :api, defaults: { format: :json } do
    resources :users, only: [:show, :update] do
      member do
        get :recommended_restaurants
        get :favorited_restaurants
      end
    end
    resources :restaurants, only: [:show] do
      member do
        get :recommended_users
      end
    end
    resources :recommended_users, only: [:index]
    resources :recommended_restaurants, only: [:index]
    resources :nationalities, only: [:index]
    resources :invites, only: [:index, :create, :destroy] do
      member do
        post :accept
        post :reject
        post :block
        post :hide
      end
    end
    resources :restaurant_favorites, only: [:create, :destroy]
    resources :chatrooms, only: [:index]
    resources :registrations, path: "register", only: [:create]
    resources :sessions, path: "login", only: [:create]

    post "/facebooks/auth", to: "facebooks#auth", as: "facebooks_auth"

    get "/explore/people", to: "explore#people", as: "explore_people"
    get "/explore/nearby", to: "explore#nearby", as: "explore_nearby"
    get "/explore/places", to: "explore#places", as: "explore_places"
    get "/explore/places_options", to: "explore#places_options", as: "explore_places_options"

    post "/check_auth", to: "tokens#check", as: "check_auth"
    get "/profile/me", to: "profile#me", as: "profile_me"
    patch "/profile/detail", to: "profile#detail", as: "profile_detail"
    patch "/profile/avatar", to: "profile#avatar", as: "profile_avatar"
    post "/profile/forgot_password", to: "profile#forgot_password", as: "profile_forgot_password"
    patch "/profile/password", to: "profile#password", as: "profile_password"
    post "/profile/photos", to: "profile/photos#create", as: "profile_photos"
    delete "/profile/photos/:id", to: "profile/photos#destroy", as: "destroy_profile_photos"
    patch "/profile/location", to: "profile#location", as: "profile_location"
    patch "/profile/deactivate", to: "profile#deactivate", as: "profile_deactivate"
  end

  resources :passwords, controller: "clearance/passwords", only: [:create, :new]
  resource :session, controller: "sessions", only: [:create]

  resources :users, controller: "clearance/users", only: [:create] do
    resource :password,
      controller: "clearance/passwords",
      only: [:create, :edit, :update]
  end

  get "/sign_in" => "clearance/sessions#new", as: "sign_in"
  delete "/sign_out" => "clearance/sessions#destroy", as: "sign_out"
end

app/models/restaurant_batch.rb
class RestaurantBatch < ActiveRecord::Base
  validates :latlong, presence: true
  validates :radius, presence: true

  has_and_belongs_to_many :restaurants
end

app/controllers/restaurant_batches_controller.rb
class RestaurantBatchesController < ApplicationController
  before_action :require_login

  def new
    @restaurant_batch = RestaurantBatch.new
  end

  def create
    @restaurant_batch = RestaurantBatch.new(restaurant_batch_params)
    if @restaurant_batch.save
      merged_params = restaurant_batch_params.merge(batch_id: @restaurant_batch.id)
      FoursquareImporterJob.perform_async(merged_params)
      redirect_to restaurant_batch_path(@restaurant_batch), notice: "Please wait while the process is running in the background"
    else
      render :new
    end
  end

  def show
    @restaurant_batch = RestaurantBatch.find(params[:id])
  end

  private
  def restaurant_batch_params
    params.require(:restaurant_batch).permit(:latlong, :radius, :batch_id)
  end
end

app/views/restaurant_batches/new.html.slim
.page-header
  .btn-toolbar.pull-right
    .btn-group
      = link_to restaurants_path, class: 'btn btn-warning' do
        i.glyphicon.glyphicon-chevron-left
        = t('button.back')
  h1
    = t :new_restaurant_from_foursquare

= simple_form_for(:restaurant_batch, url: restaurant_batches_path, html: { class: 'form-horizontal' }) do |f|
  = f.error_notification

  .col
    .col-sm-6
      = f.input :latlong, label: "Latitude Longitude"
      = f.input :radius

      .form-actions
        .form-group
          .col-sm-offset-3.col-sm-9
            = f.button :submit, class: 'btn btn-primary' do
              Save

app/views/restaurant_batches/show.html.slim
.page-header
  .btn-toolbar.pull-right
    .btn-group
      = link_to restaurants_path, class: 'btn btn-warning' do
        i.glyphicon.glyphicon-chevron-left
        = t('button.back')

  h1
    = t :show_restaurant_batch

dl.dl-horizontal
  dt
    = RestaurantBatch.human_attribute_name('latitude_longitude')
  dd
    = @restaurant_batch.latlong

dl.dl-horizontal
  dt
    = RestaurantBatch.human_attribute_name('radius')
  dd
    = "#{@restaurant_batch.radius} metres"

dl.dl-horizontal
  dt
    = RestaurantBatch.human_attribute_name('finish_importing')
  dd
    = @restaurant_batch.finished? ? "Finish" : "Still processing"

.col-sm-6
  h3 Restaurants
  table.table
    thead
      tr
        th Name
        th Address
        th.actions Actions
    tbody
      - @restaurant_batch.restaurants.each do |restaurant|
        tr
          td
            = restaurant.name
          td
            = restaurant.address
          td.actions
            = link_to restaurant, class: 'btn btn-info btn-xs' do
              span.glyphicon.glyphicon-eye-open
              | Show
            |&nbsp;