config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'
  resources :users do
    member do
      get :reset_password
      patch :activate
      patch :deactivate
    end
  end
  resources :restaurants do
    resources :photos, only: [:destroy]
    member do
      patch :activate
      patch :deactivate
    end
  end
  resources :restaurant_batches, only: [:new, :create, :show]
  resources :food_types
  resources :facilities
  resources :areas

  get "/confirm_email/:token", to: "email_confirmations#update", as: "confirm_email"

  namespace :api, defaults: { format: :json } do
    resources :users, only: [:show, :update] do
      member do
        get :recommended_restaurants
        get :favorited_restaurants
      end
    end
    resources :restaurants, only: [:show] do
      member do
        get :recommended_users
      end
    end
    resources :recommended_users, only: [:index]
    resources :recommended_restaurants, only: [:index]
    resources :nationalities, only: [:index]
    resources :invites, only: [:index, :create, :destroy] do
      member do
        post :accept
        post :reject
        post :block
        post :hide
      end
    end
    resources :restaurant_favorites, only: [:create, :destroy]
    resources :chatrooms, only: [:index]
    resources :registrations, path: "register", only: [:create]
    resources :sessions, path: "login", only: [:create]

    post "/facebooks/auth", to: "facebooks#auth", as: "facebooks_auth"

    get "/explore/people", to: "explore#people", as: "explore_people"
    get "/explore/nearby", to: "explore#nearby", as: "explore_nearby"
    get "/explore/places", to: "explore#places", as: "explore_places"
    get "/explore/places_options", to: "explore#places_options", as: "explore_places_options"

    post "/check_auth", to: "tokens#check", as: "check_auth"
    get "/profile/me", to: "profile#me", as: "profile_me"
    patch "/profile/detail", to: "profile#detail", as: "profile_detail"
    patch "/profile/avatar", to: "profile#avatar", as: "profile_avatar"
    post "/profile/forgot_password", to: "profile#forgot_password", as: "profile_forgot_password"
    patch "/profile/password", to: "profile#password", as: "profile_password"
    post "/profile/photos", to: "profile/photos#create", as: "profile_photos"
    delete "/profile/photos/:id", to: "profile/photos#destroy", as: "destroy_profile_photos"
    patch "/profile/location", to: "profile#location", as: "profile_location"
    patch "/profile/deactivate", to: "profile#deactivate", as: "profile_deactivate"
  end

  resources :passwords, controller: "clearance/passwords", only: [:create, :new]
  resource :session, controller: "sessions", only: [:create]

  resources :users, controller: "clearance/users", only: [:create] do
    resource :password,
      controller: "clearance/passwords",
      only: [:create, :edit, :update]
  end

  get "/sign_in" => "clearance/sessions#new", as: "sign_in"
  delete "/sign_out" => "clearance/sessions#destroy", as: "sign_out"
end

app/models/user.rb
class User < ActiveRecord::Base
  include Clearance::User

  attachment :avatar

  acts_as_voter

  acts_as_taggable_on :interested_ins
  acts_as_taggable_on :favorite_foods
  has_many :user_token, dependent: :destroy
  has_many :invites_by_other, -> { order("created_at desc, status asc") }, class_name: "Invite", foreign_key: :invitee_id, dependent: :destroy
  has_many :invites_by_me, -> { order("updated_at desc, status asc") }, class_name: "Invite", foreign_key: :user_id, dependent: :destroy
  has_many :photos, -> { order(updated_at: :desc) }, as: :photoable

  accepts_attachments_for :photos, attachment: :file, append: true

  enum gender: [:male, :female]
  enum residence_status: [:local, :expat, :out_of_town]
  enum interested_to_meet: [:both_male_and_female, :only_male, :only_female]
  enum payment_preference: [:anything_goes, :paying, :not_paying, :split_bill]
  enum role: [:user, :admin]

  validates_date :date_of_birth, on_or_before: lambda { 18.years.ago },
    on_or_before_message: "must be at least 18 years old"

  scope :general, -> do
    where(active: true).where("role <> ?", User.roles[:admin])
  end

  scope :nearby, -> lat, long, distance = 10_000 do
    sql_select = <<-sql_select
    users.*,
    ST_Distance(ST_GeogFromText('POINT(#{long} #{lat})'), users.location) AS distance
    sql_select
    sql = <<-sql
    ST_Dwithin(users.location::geography,
    ST_GeogFromText('POINT(#{long} #{lat})'), ?)
    sql

    select(sql_select).where(sql, distance).where(active: true).order('distance')
  end

  before_save :delete_all_associations_when_inactive
  before_save :combine_first_and_last_name
  after_create :generate_channel_group

  def self.create_from_fb_response(fb_response, email, birthday, avatar, avatar_url)
    user = User.new
    user.uid = fb_response["id"].to_s
    user.first_name = fb_response["name"].to_s.split(" ").first
    user.last_name = fb_response["name"].to_s.split(" ").second
    user.email = email
    user.gender = fb_response["gender"].to_s
    user.password = SecureRandom.hex(8)
    user.interested_to_meet = if user.gender.to_s == "male"
                                "only_female"
                              else
                                "only_male"
                              end
    user.date_of_birth = birthday
    if avatar_url.present?
      user.remote_avatar_url = avatar_url
    elsif avatar.present?
      user.avatar = avatar
    end
    user.save
    user
  end

  def self.favorited_on(restaurants, limit = 6)
    users = []
    favorited_user_ids = restaurants.map do |restaurant|
      restaurant.find_votes_for.limit(limit).pluck(:voter_id)
    end.flatten
    if !favorited_user_ids.empty?
      users = User.general.where(id: favorited_user_ids)
    end
    users
  end

  def location=(latlong)
    longlat = latlong.to_s.gsub(/\s+/, "").split(",").reverse.join(" ")
    self[:location] = "POINT (#{longlat})"
  end

  def location
    self[:location].to_s.gsub("POINT (", "").gsub(")", "").split(" ").reverse.join(", ")
  end

  def location_original
    self[:location].to_s
  end

  def long
    self[:location].to_s.gsub("POINT (", "").gsub(")", "").split(" ").first
  end

  def lat
    self[:location].to_s.gsub("POINT (", "").gsub(")", "").split(" ").second
  end

  def latitude=(latitude_coordinate)
    longitude_coordinate = long.presence || 0
    self[:location] = "POINT (#{longitude_coordinate} #{latitude_coordinate})"
  end

  def longitude=(longitude_coordinate)
    latitude_coordinate = lat.presence || 0
    self[:location] = "POINT (#{longitude_coordinate} #{latitude_coordinate})"
  end

  def age
    if date_of_birth
      ((Date.today - date_of_birth) / 365).to_i
    else
      0
    end
  end

  def humanize_nationality
    Nationality.list[self.nationality]
  end

  def generate_access_token(device_id)
    self.user_token.create(device_id: device_id,
                           token: Clearance::Token.new)
  end

  def generate_channel_group
    return channel_group if channel_group.present?

    update!(channel_group: "#{id}_#{Clearance::Token.new[0..5]}")
  end

  def confirm_email
    self.email_confirmed_at = Time.current
    save
  end

  def access_token(device_id)
    self.user_token.where(device_id: device_id).first
  end

  def chatrooms
    Invite.where("user_id = ?", self.id)
      .where(status: [Invite.statuses[:accept], Invite.statuses[:block]])
  end

  def recommended_restaurants
    Restaurant.general
      .tagged_with(favorite_food_list.split(","), on: :known_fors)
  end

  def recommended_users
    User.general
      .where.not(id: self.id)
      .where(gender: gender_preferences)
      .where(interested_to_meet: interested_to_meet_preferences)
      .order(created_at: :desc)
  end

  def explore_people(payment_preference: :anything_goes,
                     interested_in: :both_male_and_female,
                     age_from: 1, age_to: 100, interest: nil)
    age_range = age_to.to_i.years.ago.to_date..age_from.to_i.years.ago.to_date
    user = User.general
      .where.not(id: self.id)
      .where(payment_preference: user_payment_preferences(payment_preference))
      .where(gender: interested_in_preferences(interested_in))
      .where(date_of_birth: age_range)
    if interest.present?
      user = user.tagged_with(interest, on: :interested_ins, any: true, wild: true)
    end
    user.order(created_at: :desc)
  end

  def update_password_with_confirmation(password_params)
    if password_params[:password] != password_params[:password_confirmation]
      errors.add(:base, "password not match")
      false
    else
      update_password(password_params[:password])
    end
  end

  def validated_with_facebook
    !!(uid)
  end

  private
  def combine_first_and_last_name
    self.full_name = "#{self.first_name} #{self.last_name}"
  end

  def delete_all_associations_when_inactive
    if active_changed? && self.active == false
      UserToken.where(user: self).destroy_all
      Invite.where("user_id = ? OR invitee_id = ?", self.id, self.id).destroy_all
      ActsAsVotable::Vote.where(voter_id: self.id).destroy_all
    end
  end

  def interested_in_preferences(preference)
    user_gender_preferences(preference)
  end

  def gender_preferences
    user_gender_preferences(self.interested_to_meet)
  end

  def user_payment_preferences(preference)
    if preference.to_sym == :anything_goes || preference.to_sym == :paying
      [
        User.payment_preferences[:anything_goes],
        User.payment_preferences[:paying],
        User.payment_preferences[:not_paying],
        User.payment_preferences[:split_bill]
      ]
    elsif preference.to_sym == :not_paying
      [
        User.payment_preferences[:anything_goes],
        User.payment_preferences[:paying]
      ]
    elsif preference.to_sym == :split_bill
      [
        User.payment_preferences[:anything_goes],
        User.payment_preferences[:paying],
        User.payment_preferences[:split_bill]
      ]
    else
      []
    end
  end

  def user_gender_preferences(preference)
    if preference.to_sym == :both_male_and_female
      [ User.genders[:male], User.genders[:female] ]
    elsif preference.to_sym == :only_male
      [ User.genders[:male] ]
    elsif preference.to_sym == :only_female
      [ User.genders[:female] ]
    else
      []
    end
  end

  def interested_to_meet_preferences
    if self.male?
      [
        User.interested_to_meets[:both_male_and_female],
        User.interested_to_meets[:only_male]
      ]
    elsif self.female?
      [
        User.interested_to_meets[:both_male_and_female],
        User.interested_to_meets[:only_female]
      ]
    else
      []
    end
  end
end

app/controllers/api/users_controller.rb
class Api::UsersController < ApiController
  skip_before_action :verify_authenticity_token
  before_action :authenticate_token!

  def show
    @users = [User.find(params[:id])]
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      render json: {}, status: :ok
    else
      render json: { errors: @user.errors }.to_json, status: :unprocessable_entity
    end
  end

  def recommended_restaurants
    @restaurants = Restaurant.general.order(id: :desc)
    @users = User.favorited_on(@restaurants)
    @users.push(current_user)
  end

  def favorited_restaurants
    @user = User.find(params[:id])
    @restaurants = @user.get_voted(Restaurant)
    @users = User.favorited_on(@restaurants)
    @users.push(@user)
  end

  def user_params
    params.require(:user).permit(:first_name, :last_name, :username,
                                 :gender, :date_of_birth, :profession,
                                 :nationality, :residence_status,
                                 :interested_to_meet, :payment_preference,
                                 :location, :about_me)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_login

  def index
    @users = User
    if params[:search].present?
      @users = @users.fuzzy_search(params[:search])
    end
    @q = @users.ransack(params[:q])
    @users = @q.result(distinct: true)
    @users = @users.order(created_at: :desc).page(params[:page])
    authorize @users
  end

  def new
    @user = User.new
    authorize @user
  end

  def create
    @user = User.new(user_params.merge(email_confirmed_at: Time.current))
    authorize @user
    if @user.save
      redirect_to user_path(@user), info: "Success"
    else
      render :new
    end
  end

  def show
    @user = User.find(params[:id])
    authorize @user
  end

  def edit
    @user = User.find(params[:id])
    authorize @user
  end

  def reset_password
    @user = User.find(params[:id])
    authorize @user
  end

  def update
    @user = User.find(params[:id])
    authorize @user
    if @user.update(user_params)
      redirect_to user_path(@user), info: "Success"
    else
      render :edit
    end
  end

  def activate
    @user = User.find(params[:id])
    authorize @user
    @user.update(active: true)
    redirect_to users_path, info: "User activated"
  end

  def deactivate
    @user = User.find(params[:id])
    authorize @user
    @user.update(active: false)
    redirect_to users_path, info: "User deactivated"
  end

  def destroy
    @user = User.find(params[:id])
    authorize @user
    @user.destroy
    redirect_to users_path, info: "Success"
  end

  private
  def user_params
    params.require(:user).permit(:email, :password, :role, :first_name,
                                 :last_name, :username, :gender,
                                 :about_me, :date_of_birth, :profession,
                                 :nationality, :residence_status,
                                 :interested_to_meet, :payment_preference,
                                 :interested_in_list, :favorite_food_list,
                                 :location, :avatar)
  end
end

app/views/users/_filter.html.slim
= simple_form_for(:search, url: url, class: "form-horizontal", method: :get) do |f|
  .col
    .col-sm-6
      = f.input :full_name, label: "Name",
        input_html: { value: params.fetch(:search, {})[:full_name] }

      br

      .form-actions
        .form-group
          .col-sm-offset-3.col-sm-9
            = f.button :submit, t(:search), class: 'btn btn-primary'
            = link_to t(:reset), url, class: 'btn'

.clearfix
hr

app/views/users/_form.html.slim
= simple_form_for(user, html: { class: 'form-horizontal' }) do |f|
  = f.error_notification

  .col
    .col-sm-6
      - if user.new_record?
        = f.input :email
        = f.input :password, as: :password
      = f.input :role, collection: User.roles.keys, include_blank: false
      = f.input :first_name
      = f.input :last_name
      = f.input :username
      = f.input :gender, collection: User.genders.keys, include_blank: false
      = f.input :about_me
      = f.input :date_of_birth, as: :string,
        input_html: { class: "js-datepicker" }
      = f.input :profession
      = f.input :nationality, collection: Nationality.list.sort_by {|k,v| v }.map {|k,v| [v,k]}
      = f.input :residence_status, collection: User.residence_statuses.keys, include_blank: false
      = f.input :interested_to_meet, collection: User.interested_to_meets.keys, include_blank: false
      = f.input :payment_preference, collection: User.payment_preferences.keys, include_blank: false
      = f.input :location, as: :string
      = f.input :avatar, as: :attachment

      .form-actions
        .form-group
          .col-sm-offset-3.col-sm-9
            - if user.new_record?
              = f.button :submit, t(:create_user), class: 'btn btn-primary'
            - else
              = f.button :submit, t(:update_user), class: 'btn btn-primary'

app/views/users/edit.html.slim
.page-header
  .btn-toolbar.pull-right
    .btn-group
      = link_to users_path, class: 'btn btn-warning' do
        i.glyphicon.glyphicon-chevron-left
        = t('button.back')
      = link_to reset_password_user_path(@user),
        class: 'btn btn-warning' do
        i.glyphicon.glyphicon-edit
        = t('button.reset_password')
  h1
    = t :edit_user

= render "form", user: @user

app/views/users/index.html.slim
.page-header
  .btn-toolbar.pull-right
    .btn-group
      = link_to new_user_path, class: 'btn btn-primary' do
        span.glyphicon.glyphicon-plus
        = t :add_user
  h1
    = User.model_name.human
    |&nbsp;&nbsp;
    small
      span.label.label-default
        = User.count

= render 'filter', url: users_path

.table-responsive
  table.table.tile.table-striped
    thead
      tr
        th
          = sort_link(@q, :last_name)
        th
          = sort_link(@q, :first_name)
        th Email
        th
          = sort_link(@q, :created_at, "Member Since", default_order: :desc)
        th.actions Actions
    tbody
    - @users.each do |user|
      tr
        td
          = user.last_name
        td
          = user.first_name
        td
          = user.email
        td
          = I18n.l(user.created_at, format: :long)
        td.actions
          = link_to user, class: 'btn btn-info btn-xs' do
            span.glyphicon.glyphicon-eye-open
            | Show
          |&nbsp;
          = link_to edit_user_path(user), class: 'btn btn-warning btn-xs' do
            span.glyphicon.glyphicon-edit
            | Edit
          |&nbsp;
          - if !user.active?
            = link_to activate_user_path(user), method: :patch,
              data: { confirm: 'Activate this user?' },
              class: 'btn btn-info btn-xs' do
              span.glyphicon.glyphicon-edit
              | Activate
            |&nbsp;
          - else
            = link_to deactivate_user_path(user), method: :patch,
              data: { confirm: 'Deactivate this user?' },
              class: 'btn btn-danger btn-xs' do
              span.glyphicon.glyphicon-edit
              | Deactivate
            |&nbsp;

          = link_to reset_password_user_path(user),
            class: 'btn btn-warning btn-xs' do
            span.glyphicon.glyphicon-edit
            = t('button.reset_password')
          |&nbsp;
          = link_to user, method: :delete, data: { confirm: 'Are you sure?' },
            class: 'btn btn-danger btn-xs' do
            span.glyphicon.glyphicon-trash
            | Delete
          |&nbsp;

= paginate @users

app/views/users/new.html.slim
.page-header
  .btn-toolbar.pull-right
    .btn-group
      = link_to users_path, class: 'btn btn-warning' do
        i.glyphicon.glyphicon-chevron-left
        = t('button.back')
  h1
    = t :new_user

= render 'form', user: @user

app/views/users/reset_password.html.slim
.page-header
  .btn-toolbar.pull-right
    .btn-group
      = link_to users_path, class: 'btn btn-warning' do
        i.glyphicon.glyphicon-chevron-left
        = t('button.back')
  h1
    = t :reset_password_user

= simple_form_for(@user, html: { class: 'form-horizontal' }) do |f|
  = f.error_notification

  .col
    .col-sm-6
      = f.input :password, as: :password
      = f.input :password_confirmation, as: :password

      .form-actions
        .form-group
          .col-sm-offset-3.col-sm-9
            = f.button :submit, t(:reset_password), class: 'btn btn-primary'

app/views/users/show.html.slim
.page-header
  .btn-toolbar.pull-right
    .btn-group
      = link_to users_path, class: 'btn btn-warning' do
        i.glyphicon.glyphicon-chevron-left
        = t('button.back')
      = link_to edit_user_path(@user),
        class: 'btn btn-warning' do
        i.glyphicon.glyphicon-edit
        = t('button.edit')

      - if !@user.active?
        = link_to activate_user_path(@user), method: :patch,
          data: { confirm: 'Activate this user?' },
          class: 'btn btn-info' do
          span.glyphicon.glyphicon-edit
          | Activate
      - else
        = link_to deactivate_user_path(@user), method: :patch,
          data: { confirm: 'Deactivate this user?' },
          class: 'btn btn-danger' do
          span.glyphicon.glyphicon-edit
          | Deactivate

      = link_to reset_password_user_path(@user),
        class: 'btn btn-warning' do
        i.glyphicon.glyphicon-edit
        = t('button.reset_password')
      = link_to @user, :method => :delete, :data => { :confirm => 'Are you sure?' },
        class: 'btn btn-danger' do
        span.glyphicon.glyphicon-trash
        = t(:delete)
  h1
    = t :show_user

dl.dl-horizontal
  dt
    = User.human_attribute_name('active')
  dd
    = @user.active

dl.dl-horizontal
  dt
    = User.human_attribute_name('avatar')
  dd
    = attachment_image_tag(@user, :avatar, :fill, 300, 300, format: "jpg")

dl.dl-horizontal
  dt
    = User.human_attribute_name('email')
  dd
    = @user.email

dl.dl-horizontal
  dt
    = User.human_attribute_name('first_name')
  dd
    = @user.first_name

dl.dl-horizontal
  dt
    = User.human_attribute_name('last_name')
  dd
    = @user.last_name

dl.dl-horizontal
  dt
    = User.human_attribute_name('username')
  dd
    = @user.username

dl.dl-horizontal
  dt
    = User.human_attribute_name('created_at')
  dd
    = @user.created_at

dl.dl-horizontal
  dt
    = User.human_attribute_name('email')
  dd
    = @user.email

dl.dl-horizontal
  dt
    = User.human_attribute_name('gender')
  dd
    = @user.gender

dl.dl-horizontal
  dt
    = User.human_attribute_name('about_me')
  dd
    = simple_format(@user.about_me)

dl.dl-horizontal
  dt
    = User.human_attribute_name('age')
  dd
    = @user.age

dl.dl-horizontal
  dt
    = User.human_attribute_name('profession')
  dd
    = @user.profession

dl.dl-horizontal
  dt
    = User.human_attribute_name('nationality')
  dd
    = @user.humanize_nationality

dl.dl-horizontal
  dt
    = User.human_attribute_name('residence_status')
  dd
    = @user.residence_status

dl.dl-horizontal
  dt
    = User.human_attribute_name('interested_to_meet')
  dd
    = @user.interested_to_meet

dl.dl-horizontal
  dt
    = User.human_attribute_name('payment_preference')
  dd
    = @user.payment_preference