config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'
  resources :users do
    member do
      get :reset_password
      patch :activate
      patch :deactivate
    end
  end
  resources :restaurants do
    resources :photos, only: [:destroy]
    member do
      patch :activate
      patch :deactivate
    end
  end
  resources :restaurant_batches, only: [:new, :create, :show]
  resources :food_types
  resources :facilities
  resources :areas

  get "/confirm_email/:token", to: "email_confirmations#update", as: "confirm_email"

  namespace :api, defaults: { format: :json } do
    resources :users, only: [:show, :update] do
      member do
        get :recommended_restaurants
        get :favorited_restaurants
      end
    end
    resources :restaurants, only: [:show] do
      member do
        get :recommended_users
      end
    end
    resources :recommended_users, only: [:index]
    resources :recommended_restaurants, only: [:index]
    resources :nationalities, only: [:index]
    resources :invites, only: [:index, :create, :destroy] do
      member do
        post :accept
        post :reject
        post :block
        post :hide
      end
    end
    resources :restaurant_favorites, only: [:create, :destroy]
    resources :chatrooms, only: [:index]
    resources :registrations, path: "register", only: [:create]
    resources :sessions, path: "login", only: [:create]

    post "/facebooks/auth", to: "facebooks#auth", as: "facebooks_auth"

    get "/explore/people", to: "explore#people", as: "explore_people"
    get "/explore/nearby", to: "explore#nearby", as: "explore_nearby"
    get "/explore/places", to: "explore#places", as: "explore_places"
    get "/explore/places_options", to: "explore#places_options", as: "explore_places_options"

    post "/check_auth", to: "tokens#check", as: "check_auth"
    get "/profile/me", to: "profile#me", as: "profile_me"
    patch "/profile/detail", to: "profile#detail", as: "profile_detail"
    patch "/profile/avatar", to: "profile#avatar", as: "profile_avatar"
    post "/profile/forgot_password", to: "profile#forgot_password", as: "profile_forgot_password"
    patch "/profile/password", to: "profile#password", as: "profile_password"
    post "/profile/photos", to: "profile/photos#create", as: "profile_photos"
    delete "/profile/photos/:id", to: "profile/photos#destroy", as: "destroy_profile_photos"
    patch "/profile/location", to: "profile#location", as: "profile_location"
    patch "/profile/deactivate", to: "profile#deactivate", as: "profile_deactivate"
  end

  resources :passwords, controller: "clearance/passwords", only: [:create, :new]
  resource :session, controller: "sessions", only: [:create]

  resources :users, controller: "clearance/users", only: [:create] do
    resource :password,
      controller: "clearance/passwords",
      only: [:create, :edit, :update]
  end

  get "/sign_in" => "clearance/sessions#new", as: "sign_in"
  delete "/sign_out" => "clearance/sessions#destroy", as: "sign_out"
end

app/models/restaurant.rb
class Restaurant < ActiveRecord::Base
  attachment :cover

  acts_as_votable

  acts_as_taggable_on :known_fors
  validates :name, presence: true
  has_many :open_schedules, -> { order(:day).order(:time_open) }

  has_and_belongs_to_many :food_types
  has_and_belongs_to_many :facilities
  has_many :photos, as: :photoable
  belongs_to :area

  accepts_nested_attributes_for(:open_schedules, reject_if: :reject_open_schedules)
  accepts_attachments_for :photos, attachment: :file, append: true

  enum price: [
    :"0_10", :"10_20", :"20_30", :"30_40", :"40_50", :"50_75",
    :"75_100", :"100_150", :"150_200", :"200_above"
  ]

  before_save :delete_all_associations_when_inactive

  def reject_open_schedules(attributes)
    attributes["time_open"].blank? &&
      attributes["time_close"].blank?
  end

  scope :general, -> { where(active: true) }

  scope :nearby, -> lat, long, distance = 10_000 do
    sql_select = <<-sql_select
    restaurants.*,
    ST_Distance(ST_GeogFromText('POINT(#{long} #{lat})'), restaurants.location) AS distance
    sql_select
    sql = <<-sql
    ST_Dwithin(restaurants.location::geography,
    ST_GeogFromText('POINT(#{long} #{lat})'), ?)
    sql

    select(sql_select).where(sql, distance).where(active: true).order('distance')
  end

  def location=(latlong)
    longlat = latlong.to_s.gsub(/\s+/, "").split(",").reverse.join(" ")
    self[:location] = "POINT (#{longlat})"
  end

  def location
    self[:location].to_s.gsub("POINT (", "").gsub(")", "").split(" ").reverse.join(", ")
  end

  def location_original
    self[:location].to_s
  end

  def long
    self[:location].to_s.gsub("POINT (", "").gsub(")", "").split(" ").first
  end

  def lat
    self[:location].to_s.gsub("POINT (", "").gsub(")", "").split(" ").second
  end

  def self.explore_places(filter: nil,
                          food_type_ids: "",
                          facility_ids: "")
    restaurants = Restaurant.general
    food_type_restaurants = Restaurant.none
    if filter.present?
      restaurants = restaurants.fuzzy_search(name: filter)
      food_type_ids_array = FoodType.fuzzy_search(name: filter).map(&:id)
      food_type_restaurants = Restaurant.general.joins(:food_types).where(food_types_restaurants: { food_type_id: food_type_ids_array })
    end
    if food_type_ids.present?
      food_type_ids_array = food_type_ids.split(",").map(&:to_i)
      restaurants = restaurants.joins(:food_types).where(food_types_restaurants: { food_type_id: food_type_ids_array })
    end
    if facility_ids.present?
      facility_ids_array = facility_ids.split(",").map(&:to_i)
      restaurants = restaurants.joins(:facilities).where(facilities_restaurants: { facility_id: facility_ids_array })
    end
    restaurants = restaurants.limit(20).order(id: :desc)
    restaurants.concat(food_type_restaurants)
  end

  private
  def delete_all_associations_when_inactive
    if active_changed? && self.active == false
      food_types.destroy_all
      facilities.destroy_all
      ActsAsVotable::Vote.where(votable_id: self.id).destroy_all
    end
  end
end

app/controllers/api/restaurants_controller.rb
class Api::RestaurantsController < ApiController
  before_action :authenticate_token!

  def show
    restaurant = Restaurant.general.find(params[:id])
    @restaurants = [restaurant].compact
    @users = User.favorited_on(@restaurants)
    @users.push(current_user)
    @food_types = restaurant.food_types
    @facilities = restaurant.facilities
  end

  def recommended_users
    @users = User.order(id: :desc)
  end
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_action :require_login

  def index
    @restaurants = Restaurant
    if params[:search].present?
      @restaurants = @restaurants.fuzzy_search(params[:search])
    end
    @q = @restaurants.ransack(params[:q])
    @restaurants = @q.result(distinct: true)
    @restaurants = @restaurants.order(created_at: :desc).page(params[:page])
    authorize @restaurants
  end

  def new
    @restaurant = Restaurant.new
    authorize @restaurant
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)
    authorize @restaurant
    if @restaurant.save
      redirect_to restaurant_path(@restaurant), info: "Success"
    else
      render :new
    end
  end

  def show
    @restaurant = Restaurant.find(params[:id])
    authorize @restaurant
  end

  def edit
    @restaurant = Restaurant.find(params[:id])
    authorize @restaurant
  end

  def update
    @restaurant = Restaurant.find(params[:id])
    authorize @restaurant
    if @restaurant.update(restaurant_params)
      redirect_to restaurant_path(@restaurant), info: "Success"
    else
      render :edit
    end
  end


  def activate
    @restaurant = Restaurant.find(params[:id])
    authorize @restaurant
    @restaurant.update(active: true)
    redirect_to restaurants_path, info: "Restaurant activated"
  end

  def deactivate
    @restaurant = Restaurant.find(params[:id])
    authorize @restaurant
    @restaurant.update(active: false)
    redirect_to restaurants_path, info: "Restaurant deactivated"
  end

  def destroy
    @restaurant = Restaurant.find(params[:id])
    authorize @restaurant
    @restaurant.destroy
    redirect_to restaurants_path, info: "Success"
  end

  private
  def restaurant_params
    params.require(:restaurant).permit(:name, :address, :area_id,
                                       :average_cost, :people_count, :price,
                                       :known_for_list, :cover,
                                       :location, :description,
                                       :phone_number, food_type_ids: [],
                                       facility_ids: [], photos_files: [],
                                       open_schedules_attributes: [
                                         :id, :day, :hour_open,
                                         :hour_close, :time_open,
                                         :time_close, :_destroy
                                       ])
  end
end

app/views/restaurants/_filter.html.slim
= simple_form_for(:search, url: url, class: "form-horizontal", method: :get) do |f|
  .col
    .col-sm-6
      = f.input :name, label: "Name",
        input_html: { value: params.fetch(:search, {})[:name] }

      br

      .form-actions
        .form-group
          .col-sm-offset-3.col-sm-9
            = f.button :submit, t(:search), class: 'btn btn-primary'
            = link_to t(:reset), url, class: 'btn'

.clearfix
hr

app/views/restaurants/_form.html.slim
= simple_form_for(@restaurant, html: { class: 'form-horizontal' }) do |f|
  = f.error_notification

  .col
    .col-sm-6
      = f.input :cover, as: :attachment
      .form-group
        .col-sm-3.control-label
        .col-sm-9
          = attachment_image_tag(@restaurant, :cover, :fill, 300, 300, format: "jpg")
      = f.input :name
      = f.input :address
      = f.input :description
      = f.input :phone_number
      = f.association :area, collection: Area.all
      = f.input :price, collection: Restaurant.prices.keys.map {|k| [k.split("_").join(" - "), k]},
        include_blank: false
      = f.input :location, as: :string
      = f.input :known_for_list,
        input_html: { value: f.object.known_for_list.to_a.join(", ") }
      = f.association :food_types, as: :select, multiple: true,
        collection: FoodType.all, label_method: :name, value_method: :id,
        input_html: { class: "js-select2-input" }
      = f.association :facilities, as: :check_boxes,
        collection: Facility.all, label_method: :name, value_method: :id
      = f.input :photos_files, as: :attachment, multiple: true
      .form-group
        .col-sm-3.control-label
        .col-sm-9
          - @restaurant.photos.each do |photo|
            .col-md-4.col-sm-6
              .thumbnail
                = attachment_image_tag(photo, :file, :fill, 150, 150, format: "jpg")
                .caption
                  = link_to restaurant_photo_path(restaurant_id: @restaurant.id, id: photo.id), method: :delete, data: { confirm: "Are you sure?" },
                    class: "btn btn-sm btn-danger" do
                    span.glyphicon.glyphicon-trash
                    | Delete


    .col-sm-12
      h3 Open Schedules

      table.table
        thead
          tr
            th Day Open
            th Hour Open
            th Hour Close
            th Actions
        tbody
          = f.simple_fields_for :open_schedules do |open_schedule|
            = render 'open_schedule_fields', f: open_schedule
          tr#open_schedules
      .links
        = link_to_add_association "Add Open Schedule", f, :open_schedules,
          :'data-association-insertion-node' => '#open_schedules', class: 'btn btn-primary'

      .form-actions
        .form-group
          .col-sm-offset-3.col-sm-9
            = f.button :submit, class: 'btn btn-primary' do
              Save

app/views/restaurants/_open_schedule_fields.html.slim
tr.nested-fields
  td
    = f.input :id, as: :hidden
    = f.input :day, collection: OpenSchedule.days.keys, include_blank: false,
      label: false
  td
    = f.input :time_open, as: :string, label: false,
      input_html: { class: "js-time-input", value: f.object.time_open.try(:strftime, "%H:%M") }
  td
    = f.input :time_close, as: :string, label: false,
      input_html: { class: "js-time-input", value: f.object.time_close.try(:strftime, "%H:%M") }
  td
    = link_to_remove_association "remove", f, class: "btn btn-danger"

app/views/restaurants/edit.html.slim
.page-header
  .btn-toolbar.pull-right
    .btn-group
      = link_to restaurants_path, class: 'btn btn-warning' do
        i.glyphicon.glyphicon-chevron-left
        = t('button.back')
      = link_to @restaurant, class: 'btn btn-info' do
        span.glyphicon.glyphicon-eye-open
        = t(:show)
      = link_to @restaurant, :method => :delete, :data => { :confirm => 'Are you sure?' },
        class: 'btn btn-danger' do
        span.glyphicon.glyphicon-trash
        = t(:delete)
  h1
    = t :edit_restaurant

= render "form"

app/views/restaurants/index.html.slim
.page-header
  .btn-toolbar.pull-right
    .btn-group
      = link_to new_restaurant_path, class: 'btn btn-primary' do
        span.glyphicon.glyphicon-plus
        = t :add_restaurant
    .btn-group
      = link_to new_restaurant_batch_path, class: 'btn btn-primary' do
        span.glyphicon.glyphicon-plus
        = t :add_restaurant_from_foursquare
  h1
    = Restaurant.model_name.human
    |&nbsp;&nbsp;
    small
      span.label.label-default
        = Restaurant.count

= render 'filter', url: restaurants_path

.table-responsive
  table.table.tile.table-striped
    thead
      tr
        th
          = sort_link(@q, :name)
        th Address
        th
          = sort_link(@q, :created_at, "Added Since", default_order: :desc)
        th.actions Actions
    tbody
    - @restaurants.each do |restaurant|
      tr
        td
          = restaurant.name
        td
          = restaurant.address
        td
          = I18n.l(restaurant.created_at, format: :long)
        td.actions
          = link_to restaurant, class: 'btn btn-info btn-xs' do
            span.glyphicon.glyphicon-eye-open
            | Show
          |&nbsp;
          = link_to edit_restaurant_path(restaurant), class: 'btn btn-warning btn-xs' do
            span.glyphicon.glyphicon-edit
            | Edit
          |&nbsp;

          - if !restaurant.active?
            = link_to activate_restaurant_path(restaurant), method: :patch,
              data: { confirm: 'Activate this restaurant?' },
              class: 'btn btn-info btn-xs' do
              span.glyphicon.glyphicon-edit
              | Activate
            |&nbsp;
          - else
            = link_to deactivate_restaurant_path(restaurant), method: :patch,
              data: { confirm: 'Deactivate this restaurant?' },
              class: 'btn btn-danger btn-xs' do
              span.glyphicon.glyphicon-edit
              | Deactivate
            |&nbsp;

          = link_to restaurant, method: :delete, data: { confirm: 'Are you sure?' },
          class: 'btn btn-danger btn-xs' do
            span.glyphicon.glyphicon-trash
            | Delete
          |&nbsp;

= paginate @restaurants

app/views/restaurants/new.html.slim
.page-header
  .btn-toolbar.pull-right
    .btn-group
      = link_to restaurants_path, class: 'btn btn-warning' do
        i.glyphicon.glyphicon-chevron-left
        = t('button.back')
  h1
    = t :new_restaurant

= render 'form'

app/views/restaurants/show.html.slim
.page-header
  .btn-toolbar.pull-right
    .btn-group
      = link_to restaurants_path, class: 'btn btn-warning' do
        i.glyphicon.glyphicon-chevron-left
        = t('button.back')
      = link_to edit_restaurant_path(@restaurant),
        class: 'btn btn-warning' do
        i.glyphicon.glyphicon-edit
        = t('button.edit')

      - if !@restaurant.active?
        = link_to activate_restaurant_path(@restaurant), method: :patch,
          data: { confirm: 'Activate this restaurant?' },
          class: 'btn btn-info' do
          span.glyphicon.glyphicon-edit
          | Activate
      - else
        = link_to deactivate_restaurant_path(@restaurant), method: :patch,
          data: { confirm: 'Deactivate this restaurant?' },
          class: 'btn btn-danger' do
          span.glyphicon.glyphicon-edit
          | Deactivate

      = link_to @restaurant, :method => :delete, :data => { :confirm => 'Are you sure?' },
        class: 'btn btn-danger' do
        span.glyphicon.glyphicon-trash
        = t(:delete)
  h1
    = t :show_restaurant

dl.dl-horizontal
  dt
    = Restaurant.human_attribute_name('active')
  dd
    = @restaurant.active

dl.dl-horizontal
  dt
    = Restaurant.human_attribute_name('cover')
  dd
    = attachment_image_tag(@restaurant, :cover, :fill, 300, 300, format: "jpg")

dl.dl-horizontal
  dt
    = Restaurant.human_attribute_name('name')
  dd
    = @restaurant.name

dl.dl-horizontal
  dt
    = Restaurant.human_attribute_name('address')
  dd
    = @restaurant.address

dl.dl-horizontal
  dt
    = Restaurant.human_attribute_name('description')
  dd
    = simple_format(@restaurant.description)

dl.dl-horizontal
  dt
    = Restaurant.human_attribute_name('phone_number')
  dd
    = @restaurant.phone_number

dl.dl-horizontal
  dt
    = Restaurant.human_attribute_name('area')
  dd
    = @restaurant.area.try(:name)

dl.dl-horizontal
  dt
    = Restaurant.human_attribute_name('price_sgd')
  dd
    = @restaurant.price.to_s.split("_").join(" - ")

dl.dl-horizontal
  dt
    = Restaurant.human_attribute_name('known_for_list')
  dd
    = @restaurant.known_for_list.to_a.join(", ")

dl.dl-horizontal
  dt
    = Restaurant.human_attribute_name('food_types')
  dd
    = @restaurant.food_types.pluck(:name).join(", ")

dl.dl-horizontal
  dt
    = Restaurant.human_attribute_name('facilities')
  dd
    = @restaurant.facilities.pluck(:name).join(", ")

dl.dl-horizontal
  dt
    = Restaurant.human_attribute_name('location')
  dd
    = @restaurant.location

dl.dl-horizontal
  dt
    = Restaurant.human_attribute_name('photos_files')
  dd
    - @restaurant.photos.each do |photo|
      .col-md-2.col-sm-3
        .thumbnail
          = attachment_image_tag(photo, :file, :fill, 150, 150, format: "jpg")
          .caption
            = link_to restaurant_photo_path(restaurant_id: @restaurant.id, id: photo.id), method: :delete, data: { confirm: "Are you sure?" },
              class: "btn btn-sm btn-danger" do
              span.glyphicon.glyphicon-trash
              | Delete

.col-sm-6
  h3 Open Schedules
  table.table
    thead
      tr
        th Day
        th Hour Open
        th Hour Close
    tbody
      - @restaurant.open_schedules.each do |open_schedule|
        tr
          td
            = open_schedule.day
          td
            = open_schedule.time_open.try(:strftime, "%H:%M")
          td
            = open_schedule.time_close.try(:strftime, "%H:%M")