config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'
  resources :users do
    member do
      get :reset_password
      patch :activate
      patch :deactivate
    end
  end
  resources :restaurants do
    resources :photos, only: [:destroy]
    member do
      patch :activate
      patch :deactivate
    end
  end
  resources :restaurant_batches, only: [:new, :create, :show]
  resources :food_types
  resources :facilities
  resources :areas

  get "/confirm_email/:token", to: "email_confirmations#update", as: "confirm_email"

  namespace :api, defaults: { format: :json } do
    resources :users, only: [:show, :update] do
      member do
        get :recommended_restaurants
        get :favorited_restaurants
      end
    end
    resources :restaurants, only: [:show] do
      member do
        get :recommended_users
      end
    end
    resources :recommended_users, only: [:index]
    resources :recommended_restaurants, only: [:index]
    resources :nationalities, only: [:index]
    resources :invites, only: [:index, :create, :destroy] do
      member do
        post :accept
        post :reject
        post :block
        post :hide
      end
    end
    resources :restaurant_favorites, only: [:create, :destroy]
    resources :chatrooms, only: [:index]
    resources :registrations, path: "register", only: [:create]
    resources :sessions, path: "login", only: [:create]

    post "/facebooks/auth", to: "facebooks#auth", as: "facebooks_auth"

    get "/explore/people", to: "explore#people", as: "explore_people"
    get "/explore/nearby", to: "explore#nearby", as: "explore_nearby"
    get "/explore/places", to: "explore#places", as: "explore_places"
    get "/explore/places_options", to: "explore#places_options", as: "explore_places_options"

    post "/check_auth", to: "tokens#check", as: "check_auth"
    get "/profile/me", to: "profile#me", as: "profile_me"
    patch "/profile/detail", to: "profile#detail", as: "profile_detail"
    patch "/profile/avatar", to: "profile#avatar", as: "profile_avatar"
    post "/profile/forgot_password", to: "profile#forgot_password", as: "profile_forgot_password"
    patch "/profile/password", to: "profile#password", as: "profile_password"
    post "/profile/photos", to: "profile/photos#create", as: "profile_photos"
    delete "/profile/photos/:id", to: "profile/photos#destroy", as: "destroy_profile_photos"
    patch "/profile/location", to: "profile#location", as: "profile_location"
    patch "/profile/deactivate", to: "profile#deactivate", as: "profile_deactivate"
  end

  resources :passwords, controller: "clearance/passwords", only: [:create, :new]
  resource :session, controller: "sessions", only: [:create]

  resources :users, controller: "clearance/users", only: [:create] do
    resource :password,
      controller: "clearance/passwords",
      only: [:create, :edit, :update]
  end

  get "/sign_in" => "clearance/sessions#new", as: "sign_in"
  delete "/sign_out" => "clearance/sessions#destroy", as: "sign_out"
end

app/views/layouts/_flash_messages.html.slim
- flash.each do |name, msg|
  - if msg.is_a?(String)
    div class="alert alert-#{name.to_s == 'notice' ? 'success' : 'danger'}"
      button.close aria-hidden='true' data-dismiss='alert' type='button' &times;
      = content_tag :div, msg, :id => "flash_#{name}"

app/views/layouts/application.html.slim
doctype html
html
  head
    title= content_for?(:title) ? yield(:title) : "Dineconnect"
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  body
    nav.navbar.navbar-inverse.navbar-fixed-top
      .container-fluid
        .navbar-header
          button.navbar-toggle.collapsed type='button' data-toggle='collapse' data-target='#navbar' aria-expanded='false'
            span.sr-only
              | Toggle navigation
            span.icon-bar
            span.icon-bar
            span.icon-bar
          = link_to root_path, class: 'navbar-brand' do
            .glyphicon.glyphicon-scale
            |&nbsp;
            | DineConnect
        #navbar.navbar-collapse.collapse
          - if signed_in? && current_user.admin?
            ul.nav.navbar-nav
              li
                a.dropdown-toggle data-toggle='dropdown' role='button' aria-expanded='false'
                  .glyphicon.glyphicon-cog
                  |&nbsp;
                  |Menu
                  span.caret
                ul.dropdown-menu role='menu'
                  li
                    = link_to users_path do
                      .glyphicon.glyphicon-list
                      |&nbsp;
                      = User.model_name.human
                  li
                    = link_to restaurants_path do
                      .glyphicon.glyphicon-list
                      |&nbsp;
                      = Restaurant.model_name.human
                  li
                    = link_to food_types_path do
                      .glyphicon.glyphicon-list
                      |&nbsp;
                      = FoodType.model_name.human
                  li
                    = link_to facilities_path do
                      .glyphicon.glyphicon-list
                      |&nbsp;
                      = Facility.model_name.human
                  li
                    = link_to areas_path do
                      .glyphicon.glyphicon-list
                      |&nbsp;
                      = Area.model_name.human
          - if signed_in?
            ul.nav.navbar-nav.pull-right
              li
                = link_to sign_out_path, method: :delete do
                  .glyphicon.glyphicon-off
                  |&nbsp;
                  |Sign Out
    .container-fluid
      .col-sm-12.col-md-12.main
        = render partial: 'layouts/flash_messages', flash: flash
        = yield